version: '3.8'

services:
  simulation_client:
    build:
      context: .
      dockerfile: Dockerfile
    image: "${IMAGE_NAME}:${IMAGE_VERSION}"
    tty: true
    restart: always
    container_name: "${IMAGE_NAME}_${IMAGE_VERSION}"
    ports:
      - "${MQTT_PORT}:1883"
    env_file:
      - .env